const express = require('express');
const router = express.Router();
const upload = require('../services/multerService');
const { uploadDocument, uploadGuarantee,uploadInvestorDocument } = require('../controllers/uploadController');
const { getUserProfile, updateUserProfile, generateOtpForEmailChange } = require('../controllers/UserController');
const { sendEmailHandler } = require("../controllers/emailController");
const { saveDraft, submitLoan, getCompleteLoanDetails ,updateLoanDetails,getAllLoansForUser, updateLoanStatus ,getPendingRepayments,getDashboardData,uploadPaymentProof,getRepaymentsForUser} = require("../controllers/loanController");
const { saveDraftValidation, submitLoanValidation,validate } = require('../utils/loanValidation');
const { savePortfolio, getPortfolio } = require("../controllers/portfolioController");
const { getLoanOpportunities,confirmInvestment,getEarningsSchedule,setNotificationPreferences,updateLoanStatusToUnderReview ,getInvestorMonthlyROI} = require("../controllers/investorAuthController");
const { submitUserFeedback, submitInvestorFeedback } = require("../controllers/feedbackController");
const { getFAQs, addFAQ, updateFAQ, deleteFAQ } = require("../controllers/faqController");
const { createTicket, getAllTickets, getTicketById,updateTicket,
  } = require("../controllers/supportController");
const { setInterestRate,getInterestRates,getInterestRateByFrequency,updateInterestRate ,deleteInterestRate } = require("../controllers/adminController");



router.post("/send-email", sendEmailHandler);
router.get('/profile', getUserProfile);
router.patch('/update-profile', updateUserProfile);
router.post('/update-email', generateOtpForEmailChange);
router.post('/upload-documents', upload.single('file'), uploadDocument);
router.post('/upload-guarantee', upload.single('file'), uploadGuarantee);
router.post("/save-draft", saveDraftValidation,saveDraft);
router.post("/submit", submitLoanValidation, submitLoan);
router.get("/ld/:loan_id", getCompleteLoanDetails);
router.post("/update-loan-details", updateLoanDetails);
router.get("/getAllLoansForUser", getAllLoansForUser);
router.put("/update-status", updateLoanStatus);
router.patch("/saveportfolio", savePortfolio); 
router.get("/portfolio", getPortfolio); 
router.get("/oppr",getLoanOpportunities);
router.post("/confirm",confirmInvestment);
router.get("/schedule", getEarningsSchedule);
router.post("/preferences",setNotificationPreferences);
router.patch("/status",updateLoanStatusToUnderReview );
router.post("/investor-feedback", submitInvestorFeedback );
router.post("/user-feedback", submitUserFeedback );
router.get('/repayment-notification',getPendingRepayments);
router.get('/loancount',getDashboardData);
router.post('/invtdocument', upload.single('file'), uploadInvestorDocument);
router.get("/repayment-schedule",getRepaymentsForUser);
router.post("/upload-proof", upload.single("proof_file"), uploadPaymentProof);
router.get("/faq/list", getFAQs);
router.post("/faq/add", addFAQ);
router.put("/faq/update/:faq_id",  updateFAQ);
router.delete("/faq/delete/:faq_id", deleteFAQ);
router.post("/create-ticket", createTicket);
router.get("/tickets", getAllTickets);
router.get("/ticket/:ticket_id", getTicketById);
router.put("/ticket/:ticket_id", updateTicket);
router.post("/interest-rate",setInterestRate);
router.get("/interest-rates",getInterestRates);
router.get("/interest-rate/:frequency", getInterestRateByFrequency);
router.put("/upd-interest-rate/:frequency", updateInterestRate);
router.delete("/interest-rate/:frequency",deleteInterestRate);
router.get("/monthly-roi",getInvestorMonthlyROI);
module.exports = router;
